#!/bin/bash

set -e  # Exit immediately if any command exits with a non-zero status

# Get the root of the git repository
ROOT_DIR=$(git rev-parse --show-toplevel)

# Run Norminette
echo "Running Norminette..."
make -C "$ROOT_DIR" norminette
