#!/bin/bash
set -e  # Exit immediately if any command exits with a non-zero status

# Get the root of the git repository
ROOT_DIR=$(git rev-parse --show-toplevel)

Run Norminette
echo "Running Norminette..."
norminette "$ROOT_DIR"

# Build the project
echo "Building the project..."
make -C "$ROOT_DIR"
make -C "$ROOT_DIR" fclean

# # Run cppcheck
# echo "Running cppcheck..."
# make -C "$ROOT_DIR" cppcheck

# Run Clang Static Analyzer
echo "Running Clang Static Analyzer..."
make -C "$ROOT_DIR" clang_analyzer

